highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: :title.html
paginate: 5
plugins: [jekyll-paginate]
port: 4000
safe: true
url: https://dartonotes.github.io/vitae/
author: Dartono


# edit this section with your information
# jekyller.github.io - all contents run on /vitae/
# for a normal use at the base of the server change it to "/"
baseurl: /vitae/
title: Dartono's Resume
name: dartono
email: dartonotes@gmail.com
email_full: mailto:youremail@me.com
website: github.io/dartonotes
website_full: https://dartonotes.github.io/
github: trending
twitter: twitter
tel: +44 0000 000000
tel_full: tel:+440000000000
google_maps: 'https://www.google.co.uk/maps/place/44+Perth+St,+Edinburgh,+Edinburgh+City+EH3+5BL'
address:
  street: Jl Bujana Tirta 6 Blok B No 12
  postcode: 
  city: Jakarta
  country: Indonesia
google_analytics: UA-69300817-1

# needed for travis-ci build
exclude: [vendor]
